services:
  web:
    container_name: smart-key-acs__webserver
    image: nginx
    volumes:
      - ./webserver/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=backend:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 8000:80
    depends_on:
      - backend

  backend:
    container_name: smart-key-acs__webapp
    build:
      context: webapp
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./webapp:/src
    depends_on:
      -  mongo  

  mongo:
    container_name: namesmart-key-acs__db
    image: mongo